### ISSUE TITLE
REQUEST: Package Managers on the Frontend

### ISSUE THREAD

**Issue by joaojeronimo** [require-lx/community#10]
I think this would be very interesting but I would love it if someone else could give it because I don't know anything about most of these package managers. I'll propose it anyway, hopefully someone more capable will like the idea and present it :)

* node's modules and npm + browserify; -> @NeCkEr 
* RequireJS and AMD; -> @marcoscaceres 
* ES6's modules; 
* TJ's Component; -> @joaojeronimo 
* Twitter's Bower;
* Dustin Diaz' Ender;

It's more than enough, I think lots of it could be left out or be dealt with in a part II talk.

**Comment by diasdavid** [comment]
I guess now it would be more interesting to hear about WebPack

**Comment by joaojeronimo** [comment]
Yes webpack came out of the blue... I'm still wondering why, why it's any good compared to the others and what's it bringing to the table so I wish we could find someone to come talk about it

**Comment by pjanuario** [comment]
+1!

**Comment by joaojeronimo** [comment]
Well, it's now mid 2015, everything is dead except ES6 modules and Webpack am I right ?

Too bad we ended up never making this one :(

**Comment by pjanuario** [comment]
@joaojeronimo and browserify...

**Comment by joaojeronimo** [comment]
For now :P
