### ISSUE TITLE
React Crash Course 2nd edition — Let's all learn React!

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#101]
### Hosted by @sericaia and @soarez

Location: YLD HQ

Because there were so many people interested in the last React Crash Course event, we're coming back with another edition, this time bigger and better. We improved the course and added exercises that go beyond the basics.

Meetup.com - http://www.meetup.com/require-lx/events/225256560/
Facebook - https://www.facebook.com/events/175306926142518/
Twitter - https://twitter.com/requirelx/status/645719863684689920

**Comment by sericaia** [comment]
:+1: :dancer: /w @ramitos and @soarez

Let's react!

**Comment by ricardofbarros** [comment]
:+1:

**Comment by pjanuario** [comment]
:+1:

**Comment by pjanuario** [comment]
@diasdavid and @sericaia I was unable to come to the last ones, I am not sure if I am alone, but I would like to go for another one! :)
Is there video of this talks/workshops?

**Comment by sericaia** [comment]
@pjanuario, thanks for letting us know. We are joining forces to make it happen ;)

**Comment by sericaia** [comment]
@pjanuario going to announce a new crash course soon!
