### ISSUE TITLE
TALK: Go Reactive with RxJs!

### ISSUE THREAD

**Issue by ricardofbarros** [require-lx/community#102]
# about
Talk a little bit about reactive programming and [Reactive Extensions Javascript implementation](https://github.com/Reactive-Extensions/RxJS).
 I will try to explain and demo 2-4 [operators per category](http://reactivex.io/documentation/operators.html#categorized). 
And finally, see how RxJs can help you maintain code consistency & readability across your app, for instance a simple chat app demo built with React+Redux+Socket.io+etc. with and without RxJs.

**Comment by sericaia** [comment]
#react :dancer: 

:+1: :+1: :+1:

**Comment by mping** [comment]
:+1:

**Comment by ramitos** [comment]
:+1:

**Comment by xicombd** [comment]
:shipit::+1:

**Comment by pjanuario** [comment]
:+1:

**Comment by HugoDaniel** [comment]
:+1:

**Comment by JGAntunes** [comment]
:+1:

**Comment by joaojeronimo** [comment]
"Go Reactive" -> YAY IT'S ABOUT GO :D 

5 seconds later: ahhh it's about react :(

JK, :+1: !

**Comment by ricardofbarros** [comment]
@joaojeronimo it isn't about react but reactive extensions

**Comment by joaojeronimo** [comment]
"Go Reactive" -> YAY IT'S ABOUT GO :D

5 seconds later: ahhh it's about react :(

2 hours later after reading @ricardofbarros's reply: WHOA THIS IS AWESOME
