### ISSUE TITLE
TALK: Elite SVG rendering with React 

### ISSUE THREAD

**Issue by HugoDaniel** [require-lx/community#103]
This talk is about using React to render SVGs. I'll focus on providing lots of examples with varying difficulty ranging from very easy minutiae to the insanely hard stuff that fuels nightmares and children tears. Our journey will make us roam together through these alleys:

1. SVG for fun and profit (lets see how SVG works in the browser composite!)
2. React internals that help and hinder SVG rendering (lets look at their source code!)
3. Common pitfalls of mixing React and SVG (how to avoid them and the new pitfalls that come with avoiding them!)

Lets climb a mountain.

**Comment by ramitos** [comment]
:+1:

**Comment by sericaia** [comment]
:dancer: :+1:

**Comment by Soarez** [comment]
Awesome!

**Comment by diasdavid** [comment]
This looks sweet! :D
