### ISSUE TITLE
TALK: Custom React renderes

### ISSUE THREAD

**Issue by ramitos** [require-lx/community#104]
## about

React 0.14 release brought more separation between React itself and the DOM renderer. With those changes it's easier to write custom renderers - but not easy enough yet.

With this talk I'm going to show how you can write your own custom renderer by going through the [renderer I wrote for the new Apple TV](https://github.com/ramitos/react-tvml)

**Comment by fampinheiro** [comment]
:+1: bring it on

**Comment by sericaia** [comment]
YAAYYYYY :dancer:
