### ISSUE TITLE
3rd React Crash Course!

### ISSUE THREAD

**Issue by sericaia** [require-lx/community#105]
Somewhere in **January**

Hosted by @mping and @fampinheiro and provided by YLD!

Location: To be defined

There's still people interested in learning React, and many people stayed in the waiting list last two events. So, let's have another edition!

**Comment by xicombd** [comment]
\o/

**Comment by KITSRicardoBarros** [comment]
:+1:

**Comment by pjanuario** [comment]
:+1:

**Comment by JGAntunes** [comment]
:+1:

**Comment by ricardofbarros** [comment]
:+1:

**Comment by diasdavid** [comment]
I'm signing up for this one :D

**Comment by voliveira89** [comment]
:+1:

**Comment by ramitos** [comment]
:+1:

**Comment by sericaia** [comment]
We are thinking about scheduling the event to the next Wednesday, Feb 3. What do you guys think?

**Comment by pmvrmc** [comment]
Count me in :+1:

**Comment by diasdavid** [comment]
What time? :)

**Comment by diasdavid** [comment]
(Daniela says 18:30h) I'm in :)

**Comment by JGAntunes** [comment]
:+1:

**Comment by pierreozoux** [comment]
I'm in also \o/

**Comment by sericaia** [comment]
http://www.meetup.com/require-lx/events/228375264/ scheduled :)

**Comment by pjanuario** [comment]
@sericaia is it possible to record this? I am working in Amsterdam on Wednesdays. :/

**Comment by sericaia** [comment]
Hi @pjanuario ,
Sorry, I didnt saw your message.. but this is not an event to be recorded.. it's mainly practical exercices :)
