### ISSUE TITLE
Using ipscend for Static web/page publishing

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#106]
I made a thing, using IPFS, for static web/page publishing, called ipscend.

If you would like, I can show it and explain how it works :) 

tool: https://github.com/diasdavid/ipscend
post: http://blog.daviddias.me/2015/11/27/ipscend

**Comment by pierreozoux** [comment]
We could link it with: https://github.com/require-lx/community/issues/93

**Comment by xicombd** [comment]
:+1:

**Comment by JGAntunes** [comment]
:+1:  :+1:
