### ISSUE TITLE
Nodeschool International Day - Saturday, May 21, 2016

### ISSUE THREAD

**Issue by sericaia** [require-lx/community#108]
![](http://nodeschool.io/international-day/images/international-day-logo.png) 

Let's do this again? :dancer: 

I personally think that last year's edition was a huge success, at least half of the participants learned node for the first time and the other half also learned something new. What do you think?

Website: http://nodeschool.io/international-day/

**Comment by andre-duarte** [comment]
I'm in

**Comment by pmvrmc** [comment]
Count me in!

**Comment by vmlf01** [comment]
:+1:

**Comment by sericaia** [comment]
Event! http://www.meetup.com/require-lx/events/229064760/

**Comment by diasdavid** [comment]
@andre-duarte were you bouldering the other day at Vertical Wall? Your face was definitely familiar!

**Comment by andre-duarte** [comment]
@diasdavid I went to Vertical Wall on wednesday, so its was probably me. See you next time ;)

**Comment by diasdavid** [comment]
@sericaia gave a retouch on http://www.meetup.com/require-lx/events/229064760/ how is the venue going? Do we have the talk schedule set up? Do we need food and beverage sponsors?

PS: @andre-duarte was great to finally meet you the other day!

**Comment by sericaia** [comment]
#### 1. Venue
We are planning to help the event at Instituto Superior Técnico, as we have done for 3rd React Crash Course.

#### 2. Schedule
Working on it! Our idea is to have *2 tracks* (one for beginners and other for intermediate/advanced). There will be simple prizes for the best teams!

#### 3. Sponsors
We already have sponsors for it and other stuff (stickers, flyers, ...)

#### 4. Talks
If you are interested in giving a talk, please add a proposal by opening a new issue! :)
We can record it if someone has the right equipment and wants/could to do it!

#### 5. Enrolment
Yes. It was the first step 💃

**Comment by sericaia** [comment]
UPDATE: Venue Rooms booked! V1.16 and V1.17 (Civil Engineering, Instituto Superior Técnico)

**Comment by sericaia** [comment]
UPDATE: CALL FOR MENTORS/SPEAKERS!!!
https://twitter.com/requirelx/status/717788803746889728

ONE International speaker already confirmed! https://twitter.com/hveldstra

**Comment by sericaia** [comment]
UPDATE: Schedule!!! Finally our schedule for the Saturday event!

![image](https://cloud.githubusercontent.com/assets/1150553/15289553/e6b1a96e-1b6a-11e6-84e7-f0f0986488b8.png)

**Comment by sericaia** [comment]
Finally we are here http://nodeschool.io/international-day/ 💃 💃 💃 

![image](https://cloud.githubusercontent.com/assets/1150553/15376695/994f69a0-1d4e-11e6-8c93-481054628771.png)

**Comment by daviddias** [comment]
Hi everyone. A mac charger was found at the venue, if you lost one, please enter in contact with me or @sericaia to retrieve it :) (Make sure to mention with type of Mac it was :) )

**Comment by sericaia** [comment]
Thank you all for the amazing nodeschool international day event we had yesterday!

**Comment by daviddias** [comment]
Thank you @sericaia @jonhytiago and all involved for putting this together ❤️❤️❤️
