### ISSUE TITLE
registry-mirror - install npm modules from a distributed network

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#109]
## Abstract

Code management is historically a pain for developers. Maintaining a code base, manage versions, roll out upgrades, integrity guarantees, system reproducibility and other aspects a developer has to take into account, has been a struggle ever since. 

The most traditional approach when consensus seems far to reach is to put Computer Logic in software distributions, creating several layers of package management from the OS level to the Application language level, which result from very opinionated discussions from the lack of a better data model for the storage of this information.

To overcome these data distribution challenges, we created IPFS, the InterPlanetary Filesystem, a mountable and distributed file storage protocol that provides cryptographic versioning (never install the same version twice), free deduplication (avoid hitting the server several times for the same data) and distributed discovery (install modules seamlessly from your friends and colleagues machines or other people using the same module!). Modules can be also fetched faster thanks to streaming from several IPFS nodes at once (instead of the old 1 path HTTP).

IPFS is like Git meetups Bittorrent and can be used to store your most valuable collections of data, that for a Node.js developer, are their modules.

**Comment by sericaia** [comment]
👍 what do you think about giving this talk at nodeschool international day?

**Comment by sericaia** [comment]
UPDATE: Will be in our next require-lx! https://twitter.com/requirelx/status/719902700821942272

**Comment by diasdavid** [comment]
wowowow :D
