### ISSUE TITLE
TypeScript - the future of JavaScript, today!

### ISSUE THREAD

**Issue by mmv** [require-lx/community#112]
**Abstract**

TypeScript is just like the JavaScript of the future. Literally: it's JavaScript with lots of proposed changes for ES6, ES7, etc., available for use today.

It has optional typing annotations so you can make the TypeScript compiler type-check your code and find bugs for you. It works well with the existing JS ecosystem. It's so good that it's irresponsible not to use it.

TypeScript was originally built by Microsoft to help their teams make sense of large JavaScript codebases, but it's no longer a one-company's pet project. It's used and developed by many people across many organizations. It's the language that's being used by Google's team behind Angular2. It's the language that's used in Facebook to specify the ImmutableJS API.

Let's get to know TypeScript, it's differences from plain JavaScript, it's mighty advantages and why it can give you the piece of mind of strongly-typed languages while still letting you have all the advantages of JavaScript's flexibility.

**Comment by sericaia** [comment]
Let's have it in the next event 💃

**Comment by daviddias** [comment]
Really want to see this one! :D

**Comment by sericaia** [comment]
@mmv are you still interested to do this talk? :)

**Comment by mmv** [comment]
@sericaia sure!
I'll be doing the same talk at PixelsCamp, but I don't think that's a problem.

**Comment by sericaia** [comment]
What do you think about having this in October, 19? (tried to pick a date between pixelscamp and websummit)

**Comment by mmv** [comment]
It's going to be difficult because I'll be out most of October, so maybe we can point to a November meetup instead (probably after WebSummit)

**Comment by sericaia** [comment]
Postponed to November ;)

**Comment by johnytiago** [comment]
Will happen in December.

**Comment by mmv** [comment]
Delivered!
