### ISSUE TITLE
Using React, Relay and Graphql in production

### ISSUE THREAD

**Issue by fabiosantoscode** [require-lx/community#115]
Sup guys. I know the title of this issue reads "talk" but I'm proposing a series of ramblings about using the aforementioned tech in production. With my unbearably erratic speech and terrible accent I plan to not walk anyone through anything but instead shell out random advice about using these, coming from somone who shipped these to production in a website of a big British publication.

I'll also ramble about npm scripts, webpack and babel 6, because these evil confusing half-baked pieces of badly designed technology were also things I had to deal with on a daily basis, and propose that you use something proper instead.

I love you guys, bye.

**Comment by sericaia** [comment]
AWESOME!

**Comment by ricardofbarros** [comment]
@fabiosantoscode -sensei I would love to watch your talk!!

**Comment by joaojeronimo** [comment]
VEM FAZER ISSO A LONDRES MENE!!!

**Comment by sericaia** [comment]
Postponed to November :)
