### ISSUE TITLE
November nodeschool

### ISSUE THREAD

**Issue by johnytiago** [require-lx/community#117]
It would be great to have new people enrolling in the javascript journey. My suggestion would be to have SINFO hosting a require('lx') Nodeschool event. 

SINFO has the power to reach to the student community, thus captivating young students that are interested in learning NodeJS but not yet know the meetup.

SINFO's dev team as already offered to help with the mentoring.

Have any ideas? Post them bellow pls! <3

**Comment by johnytiago** [comment]
This was suggested until now:
- Since it is in a different place we should advise the regular the meetup attendees on how to park, therefore my suggestion is to start the meetup at 7pm (19h) this way avoiding EMEL's payed parking, allowing people to park freely around the campus (lots of free space).
- Book a good room, a good looking one, avoiding the old school look of most of the rooms; Lets try to get a non basement room, with good wifi.

**Comment by daviddias** [comment]
Old Shia called and he had a [message for you](https://i.ytimg.com/vi/6AnAhdN9nDg/maxresdefault.jpg)

**Comment by daviddias** [comment]
Hey @johnytiago, the meetup says it will be at IST Alameda, does this mean you have done it? https://www.meetup.com/require-lx/events/227792117/ :):)

**Comment by johnytiago** [comment]
Hey @diasdavid yeah! ;) Trying to find a room now. Will update event when it is available.

**Comment by johnytiago** [comment]
The meetup will be in the room v1.26 (Civil Block) at 6:30pm and there will be a coffee break! 🎉

**Comment by daviddias** [comment]
![image](https://cloud.githubusercontent.com/assets/1211152/20629450/8e1f3f36-b323-11e6-95c6-ceb9ce71d043.png)

# https://www.meetup.com/require-lx/events/227792117/
