### ISSUE TITLE
Sails.js

### ISSUE THREAD

**Issue by joaosa** [require-lx/community#31]
Sails.js is a MVC-like realtime web framework with a convention over configuration approach.
- Database agnostic ORM (Waterline)
- Automatic RESTful JSON API generation (Blueprints)
- Uniform request handling - both realtime and HTTP (Socket.io integration)
- Global role-based authorisation - both realtime and HTTP (Policies)
- Flexible view layouting (ejs, jade, etc)
- Automatic asset management - minification, gzipping, etc  (Linker)

I think that about 20/25min should be enough.

**Comment by tjwebb** [comment]
Hey, did you guys end up going with sails.js? Let us know if we can help.

-- the sails.js team

**Comment by daviddias** [comment]
Why close this issue? @sericaia could you clarify?

**Comment by sericaia** [comment]
This thread is dead, isn't it?
