### ISSUE TITLE
DOJO: Coding with 0MQ (Zero Message Queue) http://zeromq.org/

### ISSUE THREAD

**Issue by pjanuario** [require-lx/community#75]
After my last talk I had noticed that I hadn't time to actually show some running code and how easy is to use 0MQ, and after talking with some of the attendees I think would be nice a dojo playground (hands-on).

The idea is to have a couple of exercises to play around with the different kind of sockets, and major one to implement majordomo pattern.

**Comment by diasdavid** [comment]
NOW WITH VIDEO :D https://www.youtube.com/watch?v=84zJZrh0AIo @require-lx/community

**Comment by joaojeronimo** [comment]
wow que brutal!
