### ISSUE TITLE
nodebots of lisbon

### ISSUE THREAD

**Issue by daviddias** [require-lx/community#79]
I'm trying to gather interest around nodebots in Lisbon, know who attend and love to do some hardware hacking with Javascript.

If you don't know what nodebots is, I truly recommend watching this video from the nodebots of London folks http://vimeo.com/76806624#at=1 and read more about at nodebots.io

I've around 10 cat laser kits that were rescued from LXJS leftovers -> https://www.youtube.com/watch?v=6tOPI7YGPjM

I'm thinking in doing the similar model of nodeschool Lisbon :) 

Let me know your thoughts!

**Comment by fampinheiro** [comment]
I very interested in this topic. I was never a hardware guy an never messed with this kind of stuff but every time I see a _nodebot_ I think for myself "someday I will do something like this".

:+1:

**Comment by xicombd** [comment]
Count me in! :+1:

**Comment by diasdavid** [comment]
We should organize this one while @nneves is in Lisbon !! :D

**Comment by nneves** [comment]
I guess there's a good possibility ;) ... I have 2 talks to prepare for May, hardware stuff takes much time, let's see how this goes!
