### ISSUE TITLE
Talk Videos

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#80]
From this point forward, I'm committed to record the require('lx') talks (if the speaker is ok with it of course) you will be able to find them on this playlist

https://www.youtube.com/playlist?list=PL5-t4EqlbLPwnXpNEPQ841d4n5TRdL5xc

I'm still working to improve the setup, video quality, sound, etc, but it is a start :)

If you are an expert on video and want to contribute, please feel welcome to ping me :)

**Comment by diasdavid** [comment]
New video just released http://youtu.be/ZMMCPk_YAiE @require-lx/community

**Comment by joaojeronimo** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by pjanuario** [comment]
:+1:

**Comment by diasdavid** [comment]
Thank you :)

**Comment by diasdavid** [comment]
Just moved all of the talk videos to its own Vimeo Channel, essentially because Vimeo has an incredible better experience than what Youtube offered, I'm pretty happy and excited with capabilities like reuploading the video without breaking links or comments, add subtitles and dubs and have a way to give credit right in the platform. (Also because Google locked all my youtube videos after closing the youtube account, meh)

- Check it out at [Vimeo](https://vimeo.com/channels/requirelx)
- Arrow up on [Reddit](https://www.reddit.com/r/ioLX/comments/3evfec/requirelx_has_a_new_dedicated_video_channel)

Thank you :)
