### ISSUE TITLE
VENUE: Premium Minds

### ISSUE THREAD

**Issue by dzacarias** [require-lx/community#81]
Hey guys,

Following the meetup that took place here at Premium Minds (where I regrettably couldn't attend), I'd like to officially let you know that we loved having you here and would very much like if you'd consider us as one of your regular venues. For meetups, node schools and other events.

Any time you might need a place, just let us know and we'll set it up! 

Best,
Daniel

**Comment by pjanuario** [comment]
:+1:

**Comment by joaojeronimo** [comment]
:+1: Thanks :) We loved the venue too, the internet connection was great for the remote talk, the guys over there were kind and helped cleaning up the space afterwards :)

**Comment by dzacarias** [comment]
Great! 

On your next events, just ping us and we'll set it up. We'd be really glad to be part of your regular circuit ;-)

**Comment by diasdavid** [comment]
awesome! We definitely appreciate the support :) Let's do the next meetup there

**Comment by dzacarias** [comment]
Great

Just let us know when! :-)

**Comment by diasdavid** [comment]
@foliveira , what about having the "require('lx') goes international"(http://www.meetup.com/require-lx/events/222158151/) at Premium Minds? :) They are great hosts and it could be a great opportunity for require('lx') special guests to meet other offices and folks :) Also, Premium Minds have 5* hosts :)

**Comment by foliveira** [comment]
Hey @diasdavid! Of course yes. 

@dzacarias can we get this working? The meetup is next week (Tuesday). There's 4 talks (~2 hours) and  22 people confirmed as of now.

**Comment by dzacarias** [comment]
I'm out for vacation until tomorrow. Let me check with someone at the office and get back to you. 

Besides beer and venue, what else is needed? Thanks!

**Comment by foliveira** [comment]
@dzacarias if you guys could arrange for some light snacks and/or fruit it would be great :+1:

**Comment by dzacarias** [comment]
Ok guys. I just confirmed. We're on for next Tuesday (may 19th)

😀

**Comment by dzacarias** [comment]
@foliveira @diasdavid could you confirm on your side so we can set everything up? Thanks!

**Comment by foliveira** [comment]
@dzacarias YES! All good on our side.

Please confirm the address on the meetup page: http://www.meetup.com/require-lx/events/222158151/

**Comment by dzacarias** [comment]
Hi @foliveira 

All good, except for the floor. That's our official address, but we hold the meetups at the 2nd floor. 

Thanks!

**Comment by foliveira** [comment]
Changed on the event page.

The email went with the 1st floor address, but at least everyone was warned about the change and they can check it now in the event page

**Comment by dzacarias** [comment]
Yeah, it will be fine. We usually post notices at the building telling people where to go. Looking forward to it! :-)

**Comment by diasdavid** [comment]
I've been organizing all our data (meetups, talks and venues), added a reference to this here:

https://github.com/require-lx/community/pull/98

As always, thank you for being available to host meetups!

**Comment by dzacarias** [comment]
Of course guys!

We’re available anytime, just let us know!

Best,
Daniel
