### ISSUE TITLE
nodeschool

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#82]
![image](https://cloud.githubusercontent.com/assets/1211152/6241905/7f4e1e72-b71d-11e4-9d18-944eb0dae3a4.png)
## NODESCHOOL UPDATE - INTRODUCING FOCUS NODESCHOOL

NODESCHOOL is rad! But you know what is even rad? Learning together something new with your peers! 

So far we've been letting people pick their own nodeschool lesson for each nodeschool session and it has been a model that definitely worked out pretty great, but now, with the increased number of lessons available, the non-uniform distribution of node.js level among the community, it has been harder and harder to find a peer to tackle one of the more advanced nodeschools, and that isn't so awesome, we are like to work together. To overcome this, we are introducing a new act, FOCUS NODESCHOOL, each month we will pick one of the lessons and encourage the members present to work on that all together, you are still free to come and pick one you might want more and ask questions, but if you are keen to pick the nodeschool of the month, you will know that you will have a ton of more people to ask questions :)

**THIS MONTH IT WILL BE -> https://github.com/robertkowalski/learnyoucouchdb**

http://www.meetup.com/require-lx/events/219438288/

**Comment by joaojeronimo** [comment]
:+1:

**Comment by diasdavid** [comment]
March NodeSchool will be all about WebGL 
http://www.meetup.com/require-lx/events/219438291/
