### ISSUE TITLE
TALK: P2P Overlay Networks for Resource Discovery (CPU cycles and storage) on the Web Platform (browsers), using WebRTC as the layer of Transport

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#84]
In the last week of February I shared something I've working for a while now in OpoJS, it would be really great if you would like to hear about it as well, let me know of your thoughts :)

## Description:

WebRTC is one of the emerging technologies of the Web Platform, enabling P2P communication for private data/video transfer between browsers, however, when we talk about P2P, there is more than 15 years of heavy research on efficient P2P overlay networks that hasn’t been fully taken into account, the exploration for P2P networks architectures in the browser/WebRTC space are still far from what we know P2P can do, until…

I’ve been developing for some months now, my goal is to enable browsers to communicate and share resources (CPU cycles and storage) in a scalable P2P fashion, inspired on Chord[1] P2P algorithm (also the foundation for DynamoDB and Riak) for message routing and load distribution, following the concept of Gridlets[2], small units of data+job that can be distributed and executed in parallel.

The project current iteration is entitled webrtc-explorer(https://github.com/diasdavid/webrtc-explorer), a flexible and browser oriented Chord, which leverages all the learnings done by building webrtc-ring(https://github.com/diasdavid/webrtc-ring) and distributing raytracing jobs through several peers/browsers, most of which can be found in my blog - http://blog.daviddias.me/2014/12/20/webrtc-ring

This project is part of my MSc Thesis (currently ongoing :)) which is part of a larger Research to find and develop new ways for next generation execution environments, named Synergy-VM (http://docentes.fct.unl.pt/joao-lourenco/book/synergy-vm-0). 

[1] Chord -http://www.mendeley.com/catalog/chord-scalable-peertopeer-lookup-service-internet-applications-21/
[2] Gridlets - http://www.mendeley.com/catalog/gigi-ocean-gridlets-gridforthemasses/

**Comment by xicombd** [comment]
:+1:!

**Comment by pierreozoux** [comment]
So, you managed distributed raytracing using WebRTC, nice :)

**Comment by diasdavid** [comment]
Yes :D lot's of pokeballs ahah

**Comment by diasdavid** [comment]
Just made a tiny blogpost with an update on this http://blog.daviddias.me/2015/03/22/enter-webrtc-explorer let me know what you think :)

**Comment by diasdavid** [comment]
done - http://www.meetup.com/require-lx/events/222840436/
