### ISSUE TITLE
Build Command Line Interfaces with Node.js

### ISSUE THREAD

**Issue by daviddias** [require-lx/community#85]
I love CLIs, I find them to be extremely useful, from testing APIs to simple creating tools to combine and augment other existing CLI.

But designing and building a CLI doesn't come natural (at least not to me at first), there is to "RESTful way" of doing it, you know you have to parse arguments and create actions with those and if you can, packing some instructions would be also helpful, but which tools can help you building these? What are the patterns? Well, that is the knowledge I've been developing and that I would love to share.

Let me know if you would like to hear about this!

**Comment by pierreozoux** [comment]
:+1:

**Comment by fampinheiro** [comment]
:+1:
