### ISSUE TITLE
New idea - JS algorithm challenge

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#86]
Would it be fun if we once a month gathered to solve some code puzzles with JS, like mini 2 hour hackathons, everyone works in pairs to find the solution and in the end everyone would present their solution?

We can even have several levels, so that everyone feels welcome to join.

**Comment by joaojeronimo** [comment]
I like it, but sometimes puzzles are too abstract and I prefer to compete in more real terms, say, the first guy who builds a Facebook crawler and crawl through the most people living in portugal wins or something like that.

**Comment by diasdavid** [comment]
@joaojeronimo that sounds also like fun! I was thinking about algorithm challenges, that have specific goal, input and output.

We can always have several days for different challenges: "Algorithm Challenge" "Reverse Engineering/Hack Challenge"

**Comment by xicombd** [comment]
"Reverse Engineering/Hack Challenge" days sound awesome to me :smiley:

**Comment by joaojeronimo** [comment]
REVERSE ENGINEERING HACK CHALLENGE SOUNDS AWESOME LET'S DO IT sorry for the upper caps

So when is REHC ?

**Comment by joaojeronimo** [comment]
(another cool challenge is set out to build some kind of web service that does one task and then we benchmark all of them and see which one has the highest req/s or latency something similar)

**Comment by joaojeronimo** [comment]
(I'm can offer a 32GB 4th gen i7 server we can all run the code in, so hardware doesn't interfere with scores)
