### ISSUE TITLE
TALK: Probabilistic Data Structures

### ISSUE THREAD

**Issue by mping** [require-lx/community#88]
# intro
In this talk I want to describe a bit some data structures that can give very approximate answers with a much lower footprint than what would be required to give an exact value.

# description
Some data structures and algorithms such as HyperLogLog, Bloom Filters, etc can provide an interesting tradeoff between accuracy and memory, being ideal candidates for a range of applications.

In this talk I want to expose some of the problems of digging through large volumes of data, as well as some of the data structures that can give an approximate answer to queries such as cardinality estimation, membership, quantile, etc.

----

Although the language is dense, the talk will be light!

**Comment by foliveira** [comment]
Amazing @mping!

**Comment by pjanuario** [comment]
:+1:

**Comment by joaojeronimo** [comment]
:+1: :+1: :+1:

**Comment by JosePedroDias** [comment]
:+1:

**Comment by pierreozoux** [comment]
It was really good :) Do we have a video of the talk?

**Comment by mping** [comment]
Don't think it was taped, but here's the slides if you want: https://github.com/mping/probabilistic-data-structures

**Comment by pierreozoux** [comment]
Thanks @mping :+1:
