### ISSUE TITLE
TALK: Handling 500 million monthly active users with Node.js

### ISSUE THREAD

**Issue by jparreira** [require-lx/community#89]
My goal is to share a few lessons learned during these last 4 years scaling the Realtime Platform, from a few thousand users to over 500 million.

**Comment by pjanuario** [comment]
:+1:

**Comment by diasdavid** [comment]
:boom:

**Comment by joaojeronimo** [comment]
this one is going to be pretty cool!

**Comment by mping** [comment]
+1

**Comment by diasdavid** [comment]
https://vimeo.com/136965797
