### ISSUE TITLE
require('lx') and nodeschool of Lisbon webpages

### ISSUE THREAD

**Issue by daviddias** [require-lx/community#92]
Sometimes I wonder if it would be cool to have a `requirelx.io` or some sorts to create a better welcoming/railing experience for new members. I think github + gitter is cool and works well, but might a bit underground broadcast for some folks, thoughts?

**Comment by MalikPiarali** [comment]
I think It would be great for people like me who just started to learn how to use Git and Github or how to program.

**Comment by joaojeronimo** [comment]
Hey I have a few free hours on these days, I could make a web page that maybe fetches content from the meetup.com api to see when the next meetup is at and publish that on the webpage.

But I have -infinite design skills so we either buy a pretty bootstrap template or someone does the design ?

**Comment by joaojeronimo** [comment]
Humm... might not be trivial and need a tiny backend server, the URL `https://api.meetup.com/2/events?offset=0&format=json&limited_events=False&group_urlname=require-lx&photo-host=public&page=20&fields=&order=time&desc=false&status=upcoming&sig_id=35995312&sig=227296557b38b52c543c3222bae15c586bbcf511` will expire in 5 minutes and needs a new signed key after that :(. We need to [request a signed url in the backend server](http://www.meetup.com/pt/meetup_api/auth/#keysign).

Still doable :)

**Comment by pierreozoux** [comment]
Ok, one day, I have to introduce you to [IndieWeb](http://indiewebcamp.com/) guys!

To properly make it up, you could do it in two ways:
 - Publish (on your) Own Site, Syndicate Elsewhere. ([POSSE](http://indiewebcamp.com/POSSE))
 - Publish Elsewhere, Syndicate (to your) Own Site. ([PESOS](http://indiewebcamp.com/PESOS))

I do it on POSSE way on [Internet Freedom Meetup](https://tokoloho.co/profile/internetfreedomlisbon).

And then, the beauty is that, it is semantic web! Look at this [event](https://tokoloho.co/2015/ihavesomethingtohide---hackathon) :) I can even respond from my own website! Amazing isn't it?

If you want to start with IndieWeb, I recommend this website: [http://indiewebify.me/](http://indiewebify.me/).

I personally use [known](https://withknown.com/) as my blog engine. (PHP), but you could do it with whichever [techno](indiewebcamp.com/Projects), even jekyll or create a new one :)
If you are not afraid of PHP (I am), check this out: 
 - known: [meetup plugin](https://github.com/idno/Known/issues/766)
 - known: [facebook event plugin](https://github.com/idno/Facebook/issues/22)

The IndieWeb movement is great, I really love it's [principles](http://indiewebcamp.com/principles).

If you have any questions, please let me know, if you need hosting, I can provide it for free for you guys!

**Comment by diasdavid** [comment]
@pierreozoux you should come to require('lx') more times and talk about that stuff :)

**Comment by diasdavid** [comment]
Repo created:  https://github.com/require-lx/www :)

**Comment by daviddias** [comment]
Hi all, bringing this back. I would love to work with everyone in getting a really nice webpage for require('lx') and nodeschool of Lisbon. Currently, we have:

![image](https://cloud.githubusercontent.com/assets/1211152/19920984/b4a01066-a0d3-11e6-98fb-8b2cbcacce07.png)

and

![image](https://cloud.githubusercontent.com/assets/1211152/19920991/bc74c19c-a0d3-11e6-920e-b3515c5408ca.png)

Which is extremely poor, compared to what we could do and with the amazing talent that is present in this community.

Who would like to volunteer to help? I'm happy to volunteer to coordinate the effort and with code, but I'm not a web designer by any means, so a great help in that end would be 👌🏾. 

@joaojeronimo we can start with a bootstrap template and go from there :) 

The require('lx') www is available here: https://github.com/require-lx/www and the nodeschool is here: https://github.com/nodeschool/lisbon, hosted on the gh-pages branch
