### ISSUE TITLE
TALK: REACTivating the web

### ISSUE THREAD

**Issue by ramitos** [require-lx/community#96]
# intro

Developed by Facebook, React is a Javascript library for building user interfaces.

# description

Usually associated with its virtual DOM, React is also powerful because of its declarative style, lifecycle and non shared state: a React component describes its view at anytime. People usually find it odd because of JSX - that they eventually get used and learn to enjoy -, but it strongly encourages modularity and composition. 

----------------------------------------------------------------------------------------
In this talk we are going to get introduced to the basic principles of React.

**Comment by sericaia** [comment]
:dancer:

**Comment by joaojeronimo** [comment]
:+1:
