### ISSUE TITLE
Node Knockout Hackathon - Nov 6-8

### ISSUE THREAD

**Issue by diasdavid** [require-lx/community#97]
http://nodeknockout.com/

**Comment by diasdavid** [comment]
Who is participating on Node Knockout from Lisbon this year?

**Comment by pierreozoux** [comment]
Ok, I have something to hack on :)

#Nginx #JS SingleSignOn Hackathon for @IndieHosters ahead https://www.nginx.com/blog/launching-nginscript-and-looking-ahead/ via @michielbdejong cc @yunohost 

(republished from: https://microblog.pierre-o.fr/2015/nginx-js-singlesignon-hackathon-for-indiehosters-ahead-bloglaunching-nginscript-and-looking-ahead-via-michielbdejong )

**Comment by sericaia** [comment]
This issue is old. Gonna close it ;)
