### ISSUE TITLE
Let's celebrate 2 years of require('lx')

### ISSUE THREAD

**Issue by joaojeronimo** [require-lx/community#99]
Our first meetup was on **August 1st 2013**, `require('lx')`, the Lisbon Javascript community and the Lisbon developer community have come a very long way since then, and proper commemorations are in order.

I'd like to do something more than just the meetup and cake like last time, I also don't know what... And I'm in London which is an issue. Can we have a meetup on October 9th ? I'll be there then, probably not in time for the meetup but in time to join you guys for dinner and drinks...?

What do you guys think we should do ? Something big definitely, we're almost 500 strong and 2 years old , I'd say we're a successful developer meetup group :)

(Just noticed this is issue #99, we should commemorate our first 100 issues too!)

**Comment by diasdavid** [comment]
How long will you be in Lisbon for? :) What time do you arrive October 9th?

**Comment by joaojeronimo** [comment]
I arrive at 10:30PM :'( So I can only join you for drinks... or late dinner...?

**Comment by joaojeronimo** [comment]
I leave on Monday at 8:15 so no chance of that happening then

**Comment by diasdavid** [comment]
What about Saturday? Maybe a require(lx) sunset? :)

**Comment by joaojeronimo** [comment]
That would work but I don't know if a lot of people would already have arrangements for the weekend :(

**Comment by sericaia** [comment]
Maybe next year?!

**Comment by diasdavid** [comment]
ahah next year :)

**Comment by joaojeronimo** [comment]
:'(
